# Generated by Django 3.1.4 on 2020-12-29 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20201228_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 29, 9, 57, 8, 489096, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
